name: deploy

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: scp -i ${{ secrets.SERVER_PRIVATE_KEY }} /* ${{ secrets.USER_NAME }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/coldmodelcloud/
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
#          ARGS: '-rltgoDzvO'
#          SOURCE: ''
#          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
#          REMOTE_USER: ${{ secrets.USER_NAME }}
#          TARGET: /home/ubuntu/coldmodelcloud/
#          ${{ secrets.TARGET }}